on: push
name: CI
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types, eslint and prettier
        run: yarn lint

  test:
    name: Tests
    needs: typecheck
    env:
      LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
      NEXT_PUBLIC_API_DOMAIN: ${{ secrets.NEXT_PUBLIC_API_DOMAIN }}
      PRISMIC_API: ${{ secrets.PRISMIC_API }}
      PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
      TINY_API_TOKEN: ${{ secrets.TINY_API_TOKEN }}
      VNDA_API_TOKEN: ${{ secrets.VNDA_API_TOKEN }}
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      # - uses: microsoft/playwright-github-action@v1

      - name: Run Build
        run: yarn build

      - name: Install playwright
        run: npx playwright install chromium

      - name: Run tests
        run: yarn test:ci
