on: push
name: CI
jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types, eslint and prettier
        run: yarn lint

  # build:
  #   name: Build
  #   env:
  #     API_HOST: ${{ secrets.API_HOST }}
  #     API_IP: ${{ secrets.API_IP }}
  #     LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
  #     NEXT_PUBLIC_API_DOMAIN: ${{ secrets.NEXT_PUBLIC_API_DOMAIN }}
  #     NEXT_PUBLIC_API_PROXY: ${{ secrets.NEXT_PUBLIC_API_PROXY }}
  #     PRISMIC_API: ${{ secrets.PRISMIC_API }}
  #     PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
  #     TINY_API_TOKEN: ${{ secrets.TINY_API_TOKEN }}
  #     VNDA_API_TOKEN: ${{ secrets.VNDA_API_TOKEN }}
  #   needs: typecheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/cache@v2
  #       with:
  #         path: "**/node_modules"
  #         key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  #     - uses: actions/cache@v2
  #       with:
  #         path: "**/.next/cache"
  #         key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

  #     - name: Run Build
  #       run: yarn build

  test:
    name: Test
    # needs: build
    env:
      API_HOST: ${{ secrets.API_HOST }}
      API_IP: ${{ secrets.API_IP }}
      LOCAL_HOST: ${{ secrets.LOCAL_HOST }}
      NEXT_PUBLIC_API_DOMAIN: ${{ secrets.NEXT_PUBLIC_API_DOMAIN }}
      NEXT_PUBLIC_API_PROXY: ${{ secrets.NEXT_PUBLIC_API_PROXY }}
      PRISMIC_API: ${{ secrets.PRISMIC_API }}
      PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}
      TINY_API_TOKEN: ${{ secrets.TINY_API_TOKEN }}
      VNDA_API_TOKEN: ${{ secrets.VNDA_API_TOKEN }}
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run tests
        run: yarn test

      # - name: Upload coverage
      #   uses: codecov/codecov-action@v1.0.14
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage/lcov.info
      #     fail_ci_if_error: true
